server:
  port: 1389
  ip: 0.0.0.0
  updateinterval: 600 # interval in seconds
  cert: certs/ldap.crt
  key: certs/ldap.key
sites:
  ccf:
    site:
      name: sitename 
      user: username # user needs API permissions in ChurchTools
      password: secret1
      url: https://sitename.church.tools/
    ldap:
      o: Organisation Name
      dc: dc=myorg,dc=tld # domain components
      admincn: admin
      password: secret2
    attributes: # fields to add to user
      - name: key1
        default: defaultvalue1
        replacements: # add value to user with id
          - id: id
            value: extra
      - name: key2
        default: defaultvalue2
    adminGroup: 
      cn: "admin"
      members: # person ID of users to put in admin group
        - id 
    selectionGroupIds: # ChurchTools group IDs - only members of these groups will be served by LDAP
      - gid 
      - gid
    tranformedGroups: # ChurchTools group IDs with the group name which will be served by LDAP
      - gid: gid
        name: Groupname
        objectClass: usrObjClass # additionally set objectClass of user to that value if in group
      - gid: gid
        name: Groupname
  # further ChurchTools sites to serve - following the same schema as above