name: CI Jobs

on:
  push:
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 16.x

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js $NODE_VERSION
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install Modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js $NODE_VERSION
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install Modules
      run: npm ci
    - name: Run Unit Tests
      run: npm run test